version: '3.8'

services:
  db-mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookshop
    ports:
      - "3307:3306"
    expose:
      - "3306"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"

  backend-spring:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/bookshop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      upload-file.base-path: file:///uploads/
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      - db-mysql
      - redis
    volumes:
      - ./upload-docker/:/uploads/

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend-spring
