spring.application.name=bookhop
server.port=8080
spring.profiles.active=dev
#apiPrefix=/api/v1

#config database
spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/bookshop
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://161.248.147.127:3306/bookshop
spring.datasource.username=ellie
spring.datasource.password=Ellie123#
spring.jpa.show-sql: true


#config upload file
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#base path (use for window)
#app.upload-file.base-path=file:///D:/bookhop/upload/

app.upload-file.base-path=bookshop/upload/

#domain
app.domain=http://www.ptit.dpdns.org:8080

#jwt config
app.jwt.base64-secret=qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==
app.jwt.access-token-validity-in-seconds=8640000
app.jwt.refresh-token-validity-in-seconds=25920000

spring.data.web.pageable.one-indexed-parameters=true

#email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bookshop.dpdns.org@gmail.com
spring.mail.password=fzyhqujnhakuiimh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

#cconfig json
spring.jackson.property-naming-strategy=SNAKE_CASE